# computed from the steerability probe via renormalize_goalspace given seed data from `steerbench_converted.csv`
# and saved here for convenience. Empirical middle 95%.
reading_difficulty:
  min: 2.5
  max: 13.2
politeness:
  min: -0.14
  max: 0.14
anger:
  min: 0.01
  max: 0.328176
disgust:
  min: 0.01
  max: 0.301557
fear: 
  min: 0.01
  max: 0.295081
joy: 
  min: 0.01
  max: 0.299202
sadness: 
  min: 0.02
  max: 0.351302
surprise: 
  min: 0.01
  max: 0.333141
textual_diversity: 
  min: 50.37
  max: 244.198582
text_length: 
  min: 53.
  max: 1303.
toxicity: 
  min: 0.00
  max: 0.348171
severe_toxicity: 
  min: 0.00
  max: 0.026059
obscene: 
  min: 0.00
  max: 0.294958
threat: 
  min: 0.00
  max: 0.017384
insult: 
  min: 0.00
  max: 0.095088
identity_attack: 
  min: 0.00
  max: 0.013997