# Basic experiment info
model_id: "mistralai/Mistral-Small-3.1-24B-Instruct-2503"
probe: "./data/2025_06_steerbench_64x32.csv"
# Direct + Negative Prompt
prompt_strategy: "direct"
inst_addons:
  disambig: True
seed: 42
max_tokens: 4096
rate_limit: 128
text_gen_kwargs:
  randomness: 0.0 # temperature
  num_generations: 1
# Saving
save_as: "mistral_3_1_24b_instruct"
